baseURL = "http://fjdj.dev/"
title = "fjdj's page"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"
publishDir = "docs"

[params]
author = "fjdj"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "fjdj's personal website"
keywords = "student,developer,personal"
info = []
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2021
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = ["default", "/css/custom.css"]
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["YuGothic","'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = [
  "'self'",
  "'unsafe-inline'",
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/"
]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/fjdj-1515/"

# [[params.social]]
# name = "Gitlab"
# icon = "fa fa-2x fa-gitlab"
# weight = 2
# url = "https://gitlab.com/fjdj-1515/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/fjdj_dev/"

[[params.social]]
name = "instagram"
icon = "fa fa-2x fa-instagram"
weight = 4
url = "https://instagram.com/a2smh1/"

# [[params.social]]
# name = "LinkedIn"
# icon = "fa fa-2x fa-linkedin"
# weight = 4
# url = "https://www.linkedin.com/in/johndoe/"

# [[params.social]]
# name = "Medium"
# icon = "fa fa-2x fa-medium"
# weight = 5
# url = "https://medium.com/@johndoe"

# [[params.social]]
# name = "RSS"
# icon = "fa fa-2x fa-rss"
# weight = 6
# url = "https://myhugosite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Posts"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Links"
weight = 4
url = "links/"

# [[languages.en.menu.main]]
# name = "Contact me"
# weight = 5
# url = "contact/"

# [languages.jp]
# languageName = ":jp:"
# title = "fjdjの部屋"

[languages.jp.params]
author = "fjdj"
# info = "hogehuga"
description = "fjdj's personal website"
keywords = "student,developer,personal"

[[languages.jp.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.jp.menu.main]]
name = "Posts"
weight = 2
url = "posts/"

[[languages.jp.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.jp.menu.main]]
name = "Links"
weight = 4
url = "links/"

# [[languages.jp.menu.main]]
# name = "Contato"
# weight = 5
# url = "contact/"